version: 2
jobs:
  build:
    docker:
      - image: hurryabit/speedsheet:nightly-2019-03-10
    steps:
      - checkout

      - restore_cache:
          keys:
              - rust-2019-03-10-dirty-{{ arch }}-{{ checksum "Cargo.lock" }}
      # NOTE: Since cargo does not provide a way to only build the
      # dependencies, we clean the artifacts from the previous build first.
      # - run:
      #     name: Clean backend
      #     command: cargo clean --package speedsheet
      - run:
          name: Build backend
          command: cargo build
      - run:
          name: Style check backend
          command: cargo fmt -- --check
      - run:
          name: Lint backend
          command: cargo clippy
      - run:
          name: Unit test backend
          command: cargo test
      - save_cache:
          paths:
              - ~/.cargo
              - target
          key: rust-2019-03-10-dirty-{{ arch }}-{{ checksum "Cargo.lock" }}

      - restore_cache:
          keys:
              - yarn-1.13.0-{{ checksum "yarn.lock" }}
              - yarn-1.13.0-
      - run:
          name: Install frontend dependencies
          command: yarn install
      - save_cache:
          paths:
              - node_modules
          key: yarn-1.13.0-{{ checksum "yarn.lock" }}
      - run:
          name: Build frontend
          command: yarn build
      - run:
          name: Style check frontend
          command: yarn checkfmt
      - run:
          name: Lint frontend
          command: yarn lint

      - run:
          name: Integration test
          command: NO_CHROME_SANDBOX=1 yarn test
