version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.33.0-stretch-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
              - rust-v3-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Install rust tools
          command: |
              RUST_TOOLCHAIN=$(cat rust-toolchain)
              rustup toolchain install $RUST_TOOLCHAIN
              rustup default $RUST_TOOLCHAIN
              rustup component add rustfmt
              rustup component add clippy
      - run:
          name: Build backend
          command: cargo build
      - run:
          name: Style check backend
          command: cargo fmt -- --check
      - run:
          name: Lint backend
          command: cargo clippy
      - run:
          name: Unit test backend
          command: cargo test
      - save_cache:
          paths:
              - /usr/local/cargo/registry
              - target
          key: rust-v3-{{ arch }}-{{ checksum "Cargo.lock" }}

      - restore_cache:
          keys:
              - yarn-1.13.0-{{ checksum "yarn.lock" }}
              - yarn-1.13.0-
      - run:
          name: Install frontend dependencies
          command: yarn install
      - save_cache:
          paths:
              - node_modules
          key: yarn-1.13.0-{{ checksum "yarn.lock" }}
      - run:
          name: Build frontend
          command: yarn build
      - run:
          name: Style check frontend
          command: yarn checkfmt
      - run:
          name: Lint frontend
          command: yarn lint

      - run:
          name: Integration test
          command: NO_CHROME_SANDBOX=1 yarn test
